cma/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path('', include('products.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from . import views as v
from django.contrib.auth import views as auth_view

app_name = 'customer'

urlpatterns =[
     path('register/', v.register, name='register'),
     path('login/', v.signIn, name='login'),
     path('logout/', v.signOut, name='logout'),
     path('reset_password/', auth_view.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
          name='password_reset'),
     path('reset_password/done/', auth_view.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
          name='password_reset_done'),
     path('reset/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
          name='password_reset_confirm'),
     path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(template_name='accounts/reset_complete.html'),
          name='password_reset_complete'),

     path('customer/<int:customer_id>/', v.customer_detail, name='customer_detail'),
     path('customer/profile', v.customerProfile, name='customer_profile')
]

products/urls.py
from django.urls import path
from . import views as v

app_name = 'products'

urlpatterns =[
   path('', v.adminHomeView, name='admin_home'),
   path('ushop/', v.customerHomeView, name='customer_home'),
   path('products/', v.product_list, name='product_list'),
   path('product/add', v.add_product, name='add_product'),
   path('update_order/<str:pk>/', v.updateOrder, name='update_order'),
   
   path('create_order/', v.createOrder, name='create_order'),
   path('delete_order/<str:id>/', v.deleteOrder, name='delete_order'),
]

customer/models.py
from django.db import models
from django.contrib.auth.models import User

class CustomerProfile(models.Model):
   user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
   name = models.CharField(max_length=200, null=True)
   email = models.EmailField()
   contact = models.CharField(max_length=15)
   profile_pic = models.ImageField(null=True,blank=True)
   created_date = models.DateTimeField(auto_now_add=True)

   def __str__(self):
      return self.name

customer/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import CustomerProfile

class CreateUserForm(UserCreationForm):
   username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-sm mb-2'}))
   email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control form-control-sm mb-2'}))
   first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-sm mb-2'}))
   last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-sm mb-2'}))
   password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control form-control-sm mb-2'}))
   password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput(attrs={'class':'form-control form-control-sm mb-2'}))

   class Meta:
      model    = User
      fields   = ['username','email','first_name', 'last_name','password1','password2']

class CustomerProfileForm(forms.ModelForm):
   name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-sm'}))
   email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control form-control-sm'}))
   contact = forms.CharField(max_length=14,widget=forms.TextInput(attrs={'class':'form-control form-control-sm'}))
   profile_pic = forms.FileField(required=False, widget=forms.FileInput(attrs={'class':'form-control form-control-sm'}))

   class Meta:
      model    = CustomerProfile
      exclude   = ['user']

class SignInForm(forms.Form):
   username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-sm mb-2'}))
   password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-sm'}))

customer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate

from .filter import FilterQuerySet
from .forms import CustomerProfile, CreateUserForm, CustomerProfileForm, SignInForm
from products.forms import SearchOrderForm

def register(request):
   form = CreateUserForm(request.POST or None)
   if form.is_valid():
      form.save()
      return redirect('customer:login')
   context={
      'form':form
   }
   return render(request, 'accounts/register.html', context)

def signIn(request):
   form = SignInForm(request.POST or None)
   if form.is_valid():
      data = form.cleaned_data
      user = authenticate(username=data['username'],password=data['password'])
      if user is not None:
         login(request,user)
         return redirect('products:admin_home')
      else:
         messages.error(request,"Invalid user")
   context = {
      'form': form,
   }
   return render(request, 'accounts/login.html', context)

def signOut(request):
   logout(request)
   return redirect('customer:login')

def customer_detail(request,customer_id):
   customer = get_object_or_404(CustomerProfile,id=customer_id)
   orders = customer.order_set.all()
   order_count = orders.count()
   search_form = SearchOrderForm()
   
   if request.GET.get('refresh'):
      orders=orders
   elif request.GET.get('product') or request.GET.get('status'):
      search_obj=FilterQuerySet(
         product =request.GET.get('product'),
         status = request.GET.get('status'),
         orders_qs=orders )
      orders=search_obj.querySearch()
      search_form=SearchOrderForm(initial={'product':request.GET.get('product'), 'status':request.GET.get('status')})

   context={
      'customer':customer,
      'orders':orders,
      'order_count':order_count,
      'form':search_form,
   }
   return render(request,'accounts/customers.html', context)

def customerProfile(request):
   user = request.user.customerprofile
   form = CustomerProfileForm(instance=user)
   if request.method == 'POST':
      form = CustomerProfileForm(request.POST, request.FILES, instance=user)
      if form.is_valid():
         print(form.cleaned_data)
         form.save()

   context={
      'form':form,
   }
   return render(request, 'accounts/customer_profile.html', context)

templates/accounts/account.html
{% extends 'base.html' %} 

{% block content %}
<style>
    .profile_img {
        width: 190px;
        height:190px;
        border-radius: 50%;
        margin: auto;
        object-fit:cover;
    }
</style>

<div class="row mt-3 gy-1">
    <div class="col-md-4">
        <div class="card card-body">
            <a href="{% url 'home' %}" class="btn btn-warning btn-sm d-flex align-items-center justify-content-center">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M5.854 4.646a.5.5 0 0 1 0 .708L3.207 8l2.647 2.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 0 1 .708 0z" />
                    <path fill-rule="evenodd" d="M2.5 8a.5.5 0 0 1 .5-.5h10.5a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
                </svg>Go Back to Home</a>
            <hr />
            <h4 class="text-center">Account Setting</h4>
            <img src="{{request.user.customer.profile_pic.url}}" alt="profile.pic" class="profile_img" />
        </div>
    </div>

    <div class="col-md-8">
        <div class="card card-body">
            <form class="form" method="post" enctype="multipart/form-data">
                {% csrf_token %} {{form}}
                <input type="submit" value="Save" class="btn btn-primary btn-sm mt-2" />
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts/customer_profile.html
{% extends 'base.html' %} 

{% block content %}
<style>
    .profile_img {
        width: 190px;
        height:190px;
        border-radius: 50%;
        margin: auto;
        object-fit:cover;
    }
</style>

<div class="row align-items-center mt-3 gy-1">
    <div class="col-md-4">
        <div class="card card-body">
            <!-- <a href="{% url 'products:customer_home' %}" class="btn btn-warning btn-sm d-flex align-items-center justify-content-center">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M5.854 4.646a.5.5 0 0 1 0 .708L3.207 8l2.647 2.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 0 1 .708 0z" />
                    <path fill-rule="evenodd" d="M2.5 8a.5.5 0 0 1 .5-.5h10.5a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z" />
                </svg>Go Back to Home</a>
            <hr /> -->
            <h4 class="text-center">Profile</h4>
            <img src="{{request.user.customerprofile.profile_pic.url}}" alt="profile.pic" class="profile_img" />
        </div>
    </div>

    <div class="col-md-8">
        <div class="card card-body">
            <form class="form" method="post" enctype="multipart/form-data">
                {% csrf_token %} {{form.as_p}}
                <input type="submit" value="Save" class="btn btn-primary btn-sm mt-2" />
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts/customers.html
{% extends 'base.html' %}

{% block content %}
    <div class="row mt-3 gy-2">
        <div class="col-md-8">
            <div class="card card-body">
                <h6 class="mt-2 mb-4">Contact Information</h6>
                <span>Email: {{ customer.email }} </span>
                <span class='mt-2 mb-2'>Phone: {{ customer.contact }} </span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-body">
                <h6 class='mt-2 mb-4'>Total Orders</h6>
                <p class='display-6 text-center'> {{order_count }} </p>
            </div>
        </div>
    </div>

    <form class='mt-3 card card-body' method='get'>                        
        <div class="row">
            <div class="col-md-3 d-flex flex-column">
                {{form.product.label}}
                {{form.product}}                        
            </div>
            <div class="col-md-3 d-flex flex-column">
                {{form.status.label}}
                {{form.status}}
            </div>                        
        </div>
        <div class="d-flex mt-1 ">
            <input type='submit' class='btn btn-primary btn-sm mt-2 col-md-1' value='Search'>
            <input type='submit' class='btn btn-primary btn-sm mt-2 col-md-1 mx-2' name='refresh' value='Refresh'>
        </div>
    </form>

    <div class="row mt-4">
        <div class="col">
            <div class="card pl-1">
            <table class='table table-sm table'>
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Date Ordered</th>
                    <th>Status</th>
                    <th>Update</th>
                </tr> 
                {% for order in orders %}
                    <tr>
                        <td> {{ order.product.name }} </td>
                        <td> {{ order.product.category }} </td>
                        <td> {{ order.created_date|date }} </td>
                        <td> {{ order.status }} </td>
                        <td> <a href="{% url 'products:update_order' order.id %}" class='btn btn-sm btn-info'>Update</a> </td>
                    </tr>
                {% endfor %}         
            </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="row my-5">
        <div class="col-md-4 mx-auto">
            <div class=" card card-body">
                <h4 class='mb-4 display-6'>Login</h4>
                {% for message in messages %}
                    {% if message.tags == 'error'  %}                        
                        <p class='text-danger' >{{message}}</p>
                    {% elif message.tags == 'success' %}
                        <p class='bg-success my-1 pl-1 text-white' >{{message}}</p>
                    {% endif %}

                {% endfor %}
                <form action="" method='post' class='form'>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class='btn btn-primary btn-sm mt-2 mb-3' value="Login">                    
                </form>
                
                <small>Need an account?<a class='ml-2 text-decoration-none' href="{% url 'customer:register' %}">Sign Up</a></small> 
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/notallowed.html
{% extends 'base.html' %}

{% block content %}
    <p class='mt-3 text-center'>You have no access for this page</p>
{% endblock content %}

templates/accounts/password_reset.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-3">
    <div class="col-md-6">
        <div class="card card-body">
            <h3>Password Reset</h3>
            <p>Enter your email address below, and we’ll email instructions for setting a new one.</p>
            <form  method="post" class='form d-flex flex-column'>
                {% csrf_token %}
                {{form}}
                <input type="submit" class="btn btn-primary btn-sm mt-2" value='Reset my password'>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    <div class="row mt-3">
        <div class="col-md-8">
            <div class="card card-body">
               <h4>Enter new password</h4>
               <p>Please enter your new password twice so we can verify you typed it in correctly.</p>
                <form method="post">
                    {% csrf_token %}
                    <table class='table table-sm'>
                        <tr>
                            <td>New password</td>
                            <td>{{form.new_password1}}</td>
                        </tr>
                        <tr>
                            <td>Confirm password</td>
                            <td>{{form.new_password2}}</td>
                        </tr>
                    </table>
                    <input type="submit" value="Change my password" class='btn btn-info btn-sm mt-2'>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
<div class="row mt-3">
    <div class="col">
        <div class="card card-body">
            <h3>Password reset sent</h3>
            <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
                If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="row my-4">
        <div class="col-md-4 mx-auto">
            <div class=" card card-body">
                <h4 class='mb-4 display-6'>New Account</h4>
                <p class='text-danger' >{{form.errors}}</p>                
                <form action="" method='post' class='form'>
                    {% csrf_token %}
                    {{form.username.label}}
                    {{form.username}}
                    {{form.email.label}}
                    {{form.email}}
                    {{form.first_name.label}}
                    {{form.first_name}}
                    {{form.last_name.label}}
                    {{form.last_name}}
                    {{form.password1.label}}
                    {{form.password1}}
                    {{form.password2.label}}
                    {{form.password2}}
                    <input type="submit" class='btn btn-primary btn-sm mt-2 mb-3' value="Create Account">
                </form>
                <small>Already have an account?<a class='ml-2 text-decoration-none' href="{% url 'customer:login' %}">Sign In</a></small> 
            </div>
        </div>
    </div>
{% endblock content %}

templates/accounts/reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <div class="row mt-3">
        <div class="col-md-8">
            <div class="card card-body">
                <h4>Password reset complete</h4>
                <p>Your password has been set. You may go ahead and log in now.</p>                
                <a href="{% url 'login' %}" class="mt-2 text-decoration-none">Login</a>
            </div>
        </div>
    </div>
{% endblock content %}