cma/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path('', include('products.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from . import views as v
from django.contrib.auth import views as auth_view

app_name = 'customer'

urlpatterns =[
     path('register/', v.register, name='register'),
     path('login/', v.signIn, name='login'),
     path('logout/', v.signOut, name='logout'),
     path('reset_password/', auth_view.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
          name='password_reset'),
     path('reset_password/done/', auth_view.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
          name='password_reset_done'),
     path('reset/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
          name='password_reset_confirm'),
     path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(template_name='accounts/reset_complete.html'),
          name='password_reset_complete'),

     path('customer/<int:customer_id>/', v.customer_detail, name='customer_detail'),
     path('customer/profile', v.customerProfile, name='customer_profile')
]

products/urls.py
from django.urls import path
from . import views as v

app_name = 'products'

urlpatterns =[
   path('', v.adminHomeView, name='admin_home'),
   path('ushop/', v.customerHomeView, name='customer_home'),
   path('products/', v.product_list, name='product_list'),
   path('product/add', v.add_product, name='add_product'),
   path('update_order/<str:pk>/', v.updateOrder, name='update_order'),
   
   path('create_order/', v.createOrder, name='create_order'),
   path('delete_order/<str:id>/', v.deleteOrder, name='delete_order'),
]

products/models.py
from django.db import models
from customer.models import CustomerProfile

class Tag(models.Model):
   name = models.CharField(max_length=100)

   def __str__(self):
      return self.name

class Product(models.Model):
   CHOICE = (
      ('Indoor','Indoor'),
      ('Outdoor','Outdoor')
   )
   name  = models.CharField(max_length=100)
   price = models.DecimalField(decimal_places=2, max_digits=1000)
   category = models.CharField(max_length=100,choices=CHOICE)
   tag = models.ManyToManyField(Tag)
   added_date = models.DateTimeField(auto_now=True)

   def __str__(self):
      return self.name

class Order(models.Model):
   STATUS = (
        ('Pending', 'Pending'),
        ('Out for Delivery', 'Out for Delivery'),
        ('Delivered', 'Delivered')
    )
   customer = models.ForeignKey(CustomerProfile, on_delete=models.CASCADE)
   product = models.ForeignKey(Product, blank=True, on_delete=models.CASCADE)
   status = models.CharField(max_length=200, blank=True, choices=STATUS)
   created_date = models.DateTimeField(auto_now_add=True)

products/forms.py
from django import forms
from products.models import Order,Product,Tag

class UpdateOrderForm(forms.ModelForm):
   STATUS = (
      (None,'----------'),
      ('Pending', 'Pending'),
      ('Out for Delivery', 'Out for Delivery'),
      ('Delivered', 'Delivered')
   )
   status = forms.ChoiceField(required=False,choices=STATUS,widget=forms.Select(attrs={'class':'form-select '}))

   class Meta:
      model = Order
      exclude = ['customer','product']

class SearchOrderForm(forms.ModelForm):
   STATUS = (
      (None,'----------'),
      ('Pending', 'Pending'),
      ('Out for Delivery', 'Out for Delivery'),
      ('Delivered', 'Delivered')
   )
   product = forms.ModelChoiceField(required=False, queryset=Product.objects.all(),widget=forms.Select(attrs={'class':'form-select'}))
   status = forms.ChoiceField(required=False,choices=STATUS,widget=forms.Select(attrs={'class':'form-select '}))

   class Meta:
      model = Order
      exclude = ['customer']

class ProductAddForm(forms.ModelForm):
   CHOICE = (
      ('Indoor','Indoor'),
      ('Outdoor','Outdoor')
   )
   name = forms.CharField(label='Product', widget=forms.TextInput(attrs={'class':'form-control form-control-sm mb-2'}))
   price = forms.DecimalField(widget=forms.NumberInput(attrs={'class':'form-control form-control-sm mb-2'}))
   category = forms.ChoiceField(choices=CHOICE,widget=forms.Select(attrs={'class':'form-select '}))
   tag = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),widget=forms.SelectMultiple(attrs={'class':'form-select'}))
   
   class Meta:
      model    = Product
      fields   = '__all__'

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from customer.models import CustomerProfile
from customer.decorator import admin_only
from .forms import UpdateOrderForm, ProductAddForm
from .models import Product, Order

@login_required(login_url='customer:login')
@admin_only
def adminHomeView(request):
   order = Order.objects.all()
   customer = CustomerProfile.objects.all()
   total_order = order.count()
   delivered = Order.objects.filter(status='Delivered').count()
   pending = Order.objects.filter(status='Pending').count()

   context = {
      'orders':order,
      'total_order':total_order,
      'customer':customer,
      'delivered':delivered,
      'pending':pending,
   }
   return render(request, 'products/dashboard.html', context)

@login_required(login_url='customer:login')
def customerHomeView(request):
   orders = request.user.customerprofile.order_set.all()
   total_order = orders.count()
   delivered_count = orders.filter(status='Delivered').count()
   pending_count = orders.filter(status='Pending').count()

   context ={
      'orders':orders,
      'total_order':total_order,
      'delivered':delivered_count,
      'pending':pending_count,
   }
   return render(request, 'products/user.html', context)

@login_required(login_url='customer:login')
@admin_only
def product_list(request):
   products = Product.objects.all()
   context = {
      'products':products,
   }
   return render(request, 'products/products.html', context)

@login_required(login_url='customer:login')
def add_product(request):
   form = ProductAddForm(request.POST or None)
   if form.is_valid():
      form.save()
      return redirect('products:product_list')
   context = {
      'form':form
   }
   return render(request, 'products/add_product.html', context)

@login_required(login_url='customer:login')
def createOrder(request):
   context = {

   }
   return render(request, 'products/createOrder.html', context)

@login_required(login_url='customer:login')
def updateOrder(request,pk):
   order = get_object_or_404(Order,id=pk)
   order_form = UpdateOrderForm(request.POST or None, instance=order)
   if order_form.is_valid():
      print(order_form.cleaned_data)
      order_form.save()
      return redirect('customer:customer_detail',order.customer.id)
   context = {
      'form': order_form,
      'order': order,
   }
   return render(request, 'products/updateOrder.html', context)

@login_required(login_url='customer:login')
def deleteOrder(request,id):
   context = {

   }
   return render(request, 'products/deleteOrder.html', context)

templates/products/add_product.html
{% extends 'base.html' %}

{% block content %}
   <p class='display-5 mt-4' >Add Product</p>
   <div class='row mt-3'>
      <div class='col-md-4'>
         <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary btn-sm">Add</button>
         </form>
      </div>
   </div>
{% endblock %}

templates/products/createOrder.html
{% extends 'base.html' %}

{% block content %}
   <!-- <form class="row bg-white p-3 mt-3 g-3" method='post'>
      {% csrf_token %}
         {{ formset.management_form }}
         {% for form in formset %}
               <div class="col-md-3">
                  <label class="form-label">{{form.product.label}}</label><br>
                  {{form.product.value}}
               </div>
               <div class="col-md-3">
                  <label class="form-label">{{form.status.label}}</label><br>
                  {{form.status}}         
               </div>
               <div class="col-md-6"></div>
         {% endfor %}
         <div class="col-12">
               <input type="submit" class='btn btn-success btn-sm mt-2' value='Create Order'>
         </div>
   </form> -->
   <h4 class="mt-3">This page is coming soon.....Please be patient</h4>
{% endblock content %}

templates/products/dashboard.html
{% extends 'base.html' %}
{% block brand %}
CMA
{% endblock %}
{% block content %}
    {% include 'products/status.html' %}
    <div class="row mt-4">
        <div class="col-md-4">
            <h5>Customer</h5>
            <hr>
            <!-- <div class='border d-flex flex-fill'>
                <a class='btn btn-primary btn-sm mb-1 flex-fill'>Create Customer</a>
            </div> -->
            <table class="table table-success table-striped">
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Phone</th>
                </tr>
                {% for c in customer %}
                    <tr>
                        <td><a class='btn btn-info btn-sm' href="{% url 'customer:customer_detail' c.id %}">View</a></td>
                        <td> {{ c.name }} </a></td>
                        <td> {{ c.contact }} </td>
                    </tr>
                {% endfor %}
            </table>
        </div>

        <div class="col-md-8">
            <h5>Last 5 Orders</h5>
            <hr>            
            <table class="table table-success table-striped">
                <tr>
                    <th>Product</th>
                    <th>Date Ordered</th>
                    <th>Status</th>
                    <th>Update</th>
                </tr>
                {% for order in orders %}
                    <tr>
                        <td> {{ order.product.name }} </td>
                        <td> {{ order.created_date|date }} </td>
                        <td> {{ order.status }} </td>
                        <td> <a href="{% url 'products:update_order' order.id %}" class='btn btn-sm btn-info'>Update</a> </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock content %}

templates/products/deleteOrder.html
{% extends 'base.html' %}


{% block content %}
    <div class="row mt-3">
        <div class="col">
            <div class="card card-body">
                <p>Are you sure you want to delete item "{{ item }}"</p>
                <form class='form' method='post'>
                    {% csrf_token %}
                    <a href="{% url 'home' %}" class='btn btn-warning btn-sm'>Cancel</a>
                    <input type='submit' class='btn btn-danger btn-sm' value='Confirm'>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/products/orderForm.html
{% extends 'base.html' %}

{% block content %}
    <form class="row bg-white p-3 mt-3 g-3" method='post'>
        {% csrf_token %}
        {% if create %}
            {{ formset.management_form }}
            {% for form in formset %}
                <div class="col-md-3">
                    <label class="form-label">{{form.product.label}}</label><br>
                    {{form.product}}
                </div>
                <div class="col-md-3">
                    <label class="form-label">{{form.status.label}}</label><br>
                    {{form.status}}         
                </div>
                <div class="col-md-6"></div>
            {% endfor %}
            <div class="col-12">
                <input type="submit" class='btn btn-success btn-sm mt-2' value='Create Order'>
            </div>
        {% elif update %}
          <!--  <div class="col-md-3">
                <label class="form-label">{{form.customer.label}}</label>
                {{form.customer}}
            </div> 
            -->
            {{ form.errors}}
            <div class="col-md-3">
                <label class="form-label">{{form.product.label}}</label><br>
                {{form.product}}
            </div>
            <div class="col-md-3">
                <label class="form-label">{{form.status.label}}</label><br>
                {{form.status}}         
            </div>
            <div class="col-12">
                <input type="submit" class='btn btn-success btn-sm mt-2' value='Update Order'>
            </div>

        {% endif %}
    </form>
{% endblock content %}

templates/products/products.html
{% extends 'base.html' %}

{% block content %}
    <div class="row justify-content-between">    
        <div class="col-md-2">
            <h4 class='display-5 my-3'>Products</h4>
        </div>
        <div class="col-md-2 row align-items-end mb-1">
            <div>
                <button class="btn btn-primary btn-sm "><a href="{% url 'products:add_product' %}" style="color:white;text-decoration:none">+ADD PRODUCT</a></button>
            </div>
        </div>
    </div>
    <div class="row card">
        <div class="col">
            <table class='table '>
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Price</th>
                </tr>
                {% for i in products %}
                    <tr>
                        <td>{{ i.name }}</td>
                        <td> {{ i.category }} </td>
                        <td><strong>Rs.</strong> {{ i.price }} </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock content %}

templates/products/status.html
<div class="row mt-3 g-2">
        <div class="col-md-4">
        <div class="card text-center">
            <h5 class="card-header">Total Orders</h5>
            <div class="card-body">                
                <p class="card-text display-6"> {{ total_order }} </p>               
            </div>
            </div>
        </div>
        <div class="col-md-4">
        <div class="card text-center">
            <h5 class="card-header">Orders Delivered</h5>
            <div class="card-body">                
                <p class="card-text display-6"> {{ delivered }} </p>
            </div>
            </div>
        </div>
        <div class="col-md-4">
        <div class="card text-center">
            <h5 class="card-header">Orders Pending</h5>
            <div class="card-body">                
                <p class="card-text display-6"> {{ pending }} </p>
            </div>
            </div>
        </div>
    </div>

templates/products/updateOrder.html
{% extends 'base.html' %}

{% block content %}
   <form class="row bg-white p-3 mt-3 g-3" method='post'>
      {% csrf_token %}
      <div class="col-md-8">
      <table class="table table-borderless ">
         <tbody>
            <tr>
               <th scope="row" class="m-0">Product</th>
               <td>{{order.product.name}}</td>
            </tr>
            <tr>
               <th scope="row">Price</th>
               <td>{{order.product.price}}</td>
            </tr>
            <tr>
               <th scope="row">Status</th>
               <td>{{form.status}} {{ form.errors}}</td>
            </tr>
            <tr>
               <th></th>
               <td><input type="submit" class='btn btn-success btn-sm mt-2' value='Update Order'></td>
            </tr>
         </tbody>
         </table>
         
      </div>
   </form>
{% endblock content %}

templates/products/user.html
{% extends 'base.html' %}

{% block brand %}
UShop
{% endblock %}

{% block content %}
    {% include 'products/status.html' %}
    <button class="btn btn-primary mt-1"><a href="{% url 'products:create_order' %}" style="text-decoration:none;color:white;">Place Order</a></button>
    <div class="row mt-3">
     <div class="col">                              
            <table class="table table-success table-striped">
                <tr>
                    <th>Product</th>
                    <th>Date Ordered</th>
                    <th>Status</th>
                    <!-- <th>Update</th> -->
                    <!-- <th>Remove</th> -->
                </tr>
                {% for order in orders %}
                    <tr>
                        <td> {{ order.product.name }} </td>
                        <td> {{ order.created_date|date }} </td>
                        <td> {{ order.status }} </td>

                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock content %}