cma/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path('', include('products.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from . import views as v
from django.contrib.auth import views as auth_view

app_name = 'customer'

urlpatterns =[
     path('register/', v.register, name='register'),
     path('login/', v.signIn, name='login'),
     path('logout/', v.signOut, name='logout'),
     path('reset_password/', auth_view.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
          name='password_reset'),
     path('reset_password/done/', auth_view.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
          name='password_reset_done'),
     path('reset/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
          name='password_reset_confirm'),
     path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(template_name='accounts/reset_complete.html'),
          name='password_reset_complete'),

     path('customer/<int:customer_id>/', v.customer_detail, name='customer_detail'),
     path('customer/profile', v.customerProfile, name='customer_profile')
]

products/urls.py
from django.urls import path
from . import views as v

app_name = 'products'

urlpatterns =[
   path('', v.adminHomeView, name='admin_home'),
   path('ushop/', v.customerHomeView, name='customer_home'),
   path('products/', v.product_list, name='product_list'),
   path('product/add', v.add_product, name='add_product'),
   path('update_order/<str:pk>/', v.updateOrder, name='update_order'),
   
   path('create_order/', v.createOrder, name='create_order'),
   path('delete_order/<str:id>/', v.deleteOrder, name='delete_order'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>Customer Management App</title>    
  </head>
  <body>
    {% if request.user.is_authenticated %}
      {% include 'nav.html' %}
    {% endif %}

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>    
    <!-- Optional JavaScript -->
    <!-- Popper.js first, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    {% if request.user.groups.first.name == 'admin' %}
      <a class="navbar-brand ml-5">CMA</a>
    {% elif request.user.groups.first.name == 'customer' %}
    <a class="navbar-brand ml-5" href="{% url 'products:customer_home' %}">UShop</a>
    {% endif %}
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
    {% if request.user.is_staff %}
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" id='home' aria-current="page" href="{% url 'products:admin_home' %}">Dashboard</a>
        </li>    
        <li class="nav-item">
          <a class="nav-link" id='products' href="{% url 'products:product_list' %}">Products</a>
        </li>
      </ul>
    {% endif %}
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class='nav-link text-white'>Hello, {{request.user.username|default:'Guest'}}</a>
        </li>    
        {% if not request.user.is_staff %}
          <li class="nav-item">
            <a class='nav-link' href="{% url 'customer:customer_profile' %}">Settings</a>
          </li>    
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" id='products' href="{% url 'customer:logout' %}">Log Out</a>
        </li>
      </ul>
    </div>
  </div>
</nav>